parameters:
    counter_management.google_analytics_provider.class: ItBlaster\CounterManagementBundle\Service\Provider\GoogleAnalytics
    counter_management.yandex_metrika_provider.class: ItBlaster\CounterManagementBundle\Service\Provider\YandexMetrika
    counter_management.persisted_provider.class: ItBlaster\CounterManagementBundle\Service\Provider\Persisted
    counter_management.yandex_remote.class: ItBlaster\CounterManagementBundle\Service\Remote\YandexRemoteSource
    counter_management.google_remote.class: ItBlaster\CounterManagementBundle\Service\Remote\GoogleRemoteSource



services:

    counter_management.google_analytics_provider:
        class: %counter_management.google_analytics_provider.class%
        arguments: [@counter_management.google_remote]
        public: false
        tags:
            - { name: counter_management.provider }

    counter_management.yandex_metrika_provider:
        class: %counter_management.yandex_metrika_provider.class%
        arguments: [@counter_management.yandex_remote]
        public: false
        tags:
            - { name: counter_management.provider }

    counter_management.persisted_provider:
        class: %counter_management.persisted_provider.class%
        public: false
        tags:
            - { name: counter_management.provider }

    counter_management.yandex_remote:
        class: %counter_management.yandex_remote.class%
        arguments: [@counter_management.yandex_client]
        public: false

    counter_management.google_remote:
        class: %counter_management.google_remote.class%
        arguments: [%google_api_account_id%, %google_api_service_account%, @counter_management.google_api_client, %google_api_key%]
        public: false