parameters:
    counter_management.google_api_client.class: Google_Client
    counter_management.yandex_oauth_client.class: Yandex\OAuth\OAuthClient
    counter_management.manager.class: ItBlaster\CounterManagementBundle\Service\Manager
    counter_management.web_counter.listener.class: ItBlaster\CounterManagementBundle\Listener\WebCounterListener
    counter_management.twig_extension.class: ItBlaster\CounterManagementBundle\Twig\CounterManagementTwigExtension
    counter_management.yandex_client.class: Yandex\Metrica\Management\ManagementClient

services:

    counter_management.google_api_client:
        class: %counter_management.google_api_client.class%
        calls:
          - [setDeveloperKey, [%google_api_developer_key%] ]
          - [setApplicationName, [%google_api_application_name%] ]
          - [setClientId, ['866193973145-se05oosemb88oa3jdc7p8p61tju69k19.apps.googleusercontent.com']]
          - [setClientSecret, ['e_wZFtMHeG348wXeuZLocS0a']]

    counter_management.yandex_oauth_client:
        class: %counter_management.yandex_oauth_client.class%
        arguments: [%yandex_metrika_client_id%, %yandex_metrika_client_secret%]

    counter_management.yandex_client:
        class: %counter_management.yandex_client.class%
        arguments: [%yandex_metrika_token%]

    counter_management.manager:
        class: %counter_management.manager.class%


    counter_management.web_counter.listener:
        class: %counter_management.web_counter.listener.class%
        arguments: [@counter_management.manager, @twig]
        tags:
            - { name: propel.event_listener, class: ItBlaster\CounterManagementBundle\Model\WebCounter, event: propel.pre_insert, method: 'onPreSave' }

    counter_management.twig_extension:
        class: %counter_management.twig_extension.class%
        arguments: [@counter_management.manager]
        tags:
            - { name: twig.extension }
